name: Pull Request Notification to Discord

on:
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Check if the PR was merged
      if: github.event.pull_request.merged == true
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-Type: application/json' \
        --data '{
          "content": "**Pull Request Merged!**\n\n**Pull Request by:** [${{ github.event.pull_request.user.login }}](https://github.com/${{ github.event.pull_request.user.login }})\n**Profile URL:** [${{ github.event.pull_request.user.html_url }}]\n\n**Title:** ${{ github.event.pull_request.title }}\n**Source Branch:** `${{ github.event.pull_request.head.ref }}`\n**Target Branch:** `${{ github.event.pull_request.base.ref }}`\n\n**URL:** [View Pull Request](${{ github.event.pull_request.html_url }})\n\n**Merged by:** [${{ github.event.pull_request.merged_by.login }}](https://github.com/${{ github.event.pull_request.merged_by.login }})"
        }' $DISCORD_WEBHOOK_URL
