name: Pull Request Notification to Discord

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord notification
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-Type: application/json' \
        --data '{
          "content": "New pull request created by **${{ github.event.pull_request.user.login }}**:\n**Title:** ${{ github.event.pull_request.title }}\n**URL:** ${{ github.event.pull_request.html_url }}"
        }' $DISCORD_WEBHOOK_URL
